[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"
headless = true

[theme]
base = "light"
primaryColor = "#547565"
backgroundColor = "#FAF8F2"
secondaryBackgroundColor = "#EEECE2"
textColor = "#273B35"
